# Generated by Django 2.2 on 2020-05-06 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
    ]
