# Generated by Django 2.2 on 2020-05-14 09:57

import api_basebone.core.fields
from django.db import migrations, models
import django.db.models.deletion


def delete_chart_templates(apps, schema_editor):
    MetricTemplate = apps.get_model("chart", "MetricTemplate")
    MetricTemplate.objects.using(schema_editor.connection.alias).all().delete()
    DimensionTemplate = apps.get_model("chart", "DimensionTemplate")
    DimensionTemplate.objects.using(schema_editor.connection.alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0003_auto_20200507_1613'),
    ]

    operations = [
        migrations.RunPython(delete_chart_templates, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='charttemplate',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='charttemplate',
            name='metrics',
        ),
        migrations.AddField(
            model_name='dimensiontemplate',
            name='template',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='chart.ChartTemplate', verbose_name='模板'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metrictemplate',
            name='template',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='chart.ChartTemplate', verbose_name='模板'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='charttemplate',
            name='image',
            field=api_basebone.core.fields.BoneImageUrlField(verbose_name='示例'),
        ),
    ]
