# Generated by Django 2.2.9 on 2020-05-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0004_auto_20200514_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimensiontemplate',
            name='required',
            field=models.BooleanField(default=True, verbose_name='必填'),
        ),
    ]
