# Generated by Django 2.2.9 on 2020-05-16 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0005_dimensiontemplate_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='chart.ChartTemplate', verbose_name='图表模板'),
        ),
        migrations.CreateModel(
            name='MetricArgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=30, verbose_name='字段')),
                ('method', models.CharField(max_length=20, verbose_name='聚合函数')),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_args', to='chart.Chart', verbose_name='图表')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='args', to='chart.MetricTemplate', verbose_name='指标模板')),
            ],
            options={
                'verbose_name': '指标参数',
                'verbose_name_plural': '指标参数',
                'unique_together': {('chart', 'template')},
            },
        ),
        migrations.CreateModel(
            name='DimensionArgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=30, verbose_name='字段')),
                ('method', models.CharField(blank=True, max_length=20, verbose_name='聚合函数')),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimension_args', to='chart.Chart', verbose_name='图表')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='args', to='chart.DimensionTemplate', verbose_name='维度模板')),
            ],
            options={
                'verbose_name': '指标参数',
                'verbose_name_plural': '指标参数',
                'unique_together': {('chart', 'template')},
            },
        ),
    ]
