# Generated by Django 2.2.9 on 2020-05-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0006_auto_20200516_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension',
            name='method',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='统计精度函数（当field类型时时间时会有）'),
        ),
        migrations.AlterField(
            model_name='dimensionargs',
            name='method',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='聚合函数'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='method',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='聚合函数'),
        ),
        migrations.AlterField(
            model_name='metricargs',
            name='method',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='聚合函数'),
        ),
        migrations.AlterUniqueTogether(
            name='dimensionargs',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='metricargs',
            unique_together=set(),
        ),
    ]
