# Generated by Django 2.2.9 on 2020-05-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0007_auto_20200516_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimensionargs',
            name='display_name',
            field=models.CharField(default=None, max_length=30, verbose_name='维度名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metric',
            name='format',
            field=models.CharField(default='{}', max_length=50, verbose_name='格式'),
        ),
        migrations.AddField(
            model_name='metricargs',
            name='display_name',
            field=models.CharField(default=None, max_length=30, verbose_name='指标名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metricargs',
            name='format',
            field=models.CharField(default='{}', max_length=50, verbose_name='格式'),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='display_name',
            field=models.CharField(max_length=30, verbose_name='维度名称'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='display_name',
            field=models.CharField(max_length=30, verbose_name='指标名称'),
        ),
    ]
