# Generated by Django 2.2.9 on 2020-05-21 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0008_auto_20200518_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension',
            name='field',
            field=models.CharField(max_length=100, verbose_name='字段'),
        ),
        migrations.AlterField(
            model_name='dimensionargs',
            name='field',
            field=models.CharField(max_length=100, verbose_name='字段'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='field',
            field=models.CharField(max_length=100, verbose_name='字段'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='field',
            field=models.CharField(max_length=100, verbose_name='字段'),
        ),
        migrations.AlterField(
            model_name='metricargs',
            name='field',
            field=models.CharField(max_length=100, verbose_name='字段'),
        ),
    ]
