# Generated by Django 2.2.9 on 2020-06-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0009_auto_20200521_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='template',
        ),
        migrations.AddField(
            model_name='chart',
            name='template_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='模板'),
        ),
    ]
