# Generated by Django 2.2.9 on 2020-06-27 10:52

import api_basebone.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0011_auto_20200612_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='sort_keys',
            field=api_basebone.core.fields.JSONField(default=[], verbose_name='排序字段'),
        ),
        migrations.AddField(
            model_name='chart',
            name='sort_type',
            field=models.CharField(blank=True, choices=[('asce', '升序'), ('dest', '降序')], default=None, max_length=50, null=True, verbose_name='排序类型'),
        ),
        migrations.AddField(
            model_name='chart',
            name='top_max',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='显示前几条'),
        ),
    ]
