# Generated by Django 2.2.9 on 2020-06-30 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0013_auto_20200629_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='sort_type',
        ),
        migrations.AlterField(
            model_name='filter',
            name='chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_filters', to='chart.Chart', verbose_name='图表'),
        ),
    ]
