# Generated by Django 2.2.9 on 2020-10-28 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0001_initial'),
        ('chart', '0015_auto_20200710_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='puzzle.Block')),
                ('display_name', models.CharField(max_length=30, verbose_name='名称')),
                ('model', models.CharField(max_length=200, verbose_name='模型')),
                ('field', models.CharField(max_length=100, verbose_name='字段')),
                ('method', models.CharField(choices=[['Sum', '累加'], ['Count', '计数'], ['Avg', '平均值'], ['Max', '最大值'], ['Min', '最小值']], max_length=20, verbose_name='聚合函数')),
                ('prefix', models.CharField(blank=True, default='', max_length=10, verbose_name='前缀')),
                ('postfix', models.CharField(blank=True, default='', max_length=10, verbose_name='后缀')),
            ],
            options={
                'verbose_name': '统计',
                'verbose_name_plural': '统计',
            },
            bases=('puzzle.block',),
        ),
        migrations.AddField(
            model_name='chart',
            name='block',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='puzzle.Block', verbose_name='渲染结点'),
        ),
        migrations.CreateModel(
            name='StatisticFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100, verbose_name='字段')),
                ('operator', models.CharField(max_length=20, verbose_name='条件判断符')),
                ('value', models.CharField(max_length=100, verbose_name='条件值')),
                ('statistic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='chart.Statistic', verbose_name='统计')),
            ],
            options={
                'verbose_name': '查询条件',
                'verbose_name_plural': '查询条件',
            },
        ),
    ]
