# Generated by Django 2.2.9 on 2020-10-29 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0001_initial'),
        ('chart', '0016_auto_20201028_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartCard',
            fields=[
                ('block_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='puzzle.Block')),
                ('model', models.CharField(max_length=200, verbose_name='模型')),
                ('field', models.CharField(max_length=100, verbose_name='字段')),
                ('chart_style', models.CharField(max_length=20, verbose_name='图表样式')),
                ('main_chart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chart.Chart', verbose_name='主图表')),
            ],
            options={
                'verbose_name': '统计卡片',
                'verbose_name_plural': '统计卡片',
            },
            bases=('puzzle.block',),
        ),
        migrations.CreateModel(
            name='ChartCardMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=30, verbose_name='名称')),
                ('method', models.CharField(choices=[['Sum', '累加'], ['Count', '计数'], ['Avg', '平均值'], ['Max', '最大值'], ['Min', '最小值']], max_length=20, verbose_name='聚合函数')),
                ('prefix', models.CharField(blank=True, default='', max_length=10, verbose_name='前缀')),
                ('postfix', models.CharField(blank=True, default='', max_length=10, verbose_name='后缀')),
            ],
            options={
                'verbose_name': '卡片统计指标',
                'verbose_name_plural': '卡片统计指标',
            },
        ),
        migrations.CreateModel(
            name='ChartCardFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100, verbose_name='字段')),
                ('operator', models.CharField(max_length=20, verbose_name='条件判断符')),
                ('value', models.CharField(max_length=100, verbose_name='条件值')),
                ('chard_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='chart.ChartCard', verbose_name='统计卡片')),
            ],
            options={
                'verbose_name': '查询条件',
                'verbose_name_plural': '查询条件',
            },
        ),
        migrations.AddField(
            model_name='chartcard',
            name='primary_metric',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='primary_cards', to='chart.ChartCardMetric', verbose_name='主指标'),
        ),
        migrations.AddField(
            model_name='chartcard',
            name='secondary_metric',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_cards', to='chart.ChartCardMetric', verbose_name='副指标'),
        ),
    ]
