# Generated by Django 2.2.9 on 2020-11-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0017_auto_20201029_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartcard',
            name='chart_style',
        ),
        migrations.RemoveField(
            model_name='chartcard',
            name='main_chart',
        ),
        migrations.AddField(
            model_name='chartcard',
            name='chart_x',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='图表X轴'),
        ),
        migrations.AddField(
            model_name='chartcard',
            name='chart_x_method',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='图表X轴函数'),
        ),
        migrations.AddField(
            model_name='chartcard',
            name='chart_y',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='图表Y轴'),
        ),
        migrations.AddField(
            model_name='chartcard',
            name='chart_y_method',
            field=models.CharField(blank=True, choices=[('Sum', '累加'), ('Count', '计数'), ('Avg', '平均值'), ('Max', '最大值'), ('Min', '最小值')], max_length=20, null=True, verbose_name='图表Y轴函数'),
        ),
        migrations.AddField(
            model_name='chartcard',
            name='help',
            field=models.CharField(max_length=200, null=True, verbose_name='提示信息'),
        ),
        migrations.AddField(
            model_name='chartcard',
            name='style',
            field=models.CharField(choices=[['statistic', '数值样式'], ['lineFill', '曲线填充图'], ['columnTree', '柱形树状图'], ['progressBar', '进度条']], default=1, max_length=20, verbose_name='图表样式'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chartcardmetric',
            name='method',
            field=models.CharField(choices=[('Sum', '累加'), ('Count', '计数'), ('Avg', '平均值'), ('Max', '最大值'), ('Min', '最小值')], max_length=20, verbose_name='聚合函数'),
        ),
    ]
