# Generated by Django 2.2.9 on 2021-01-29 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0019_auto_20201124_0344'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartFormFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100, verbose_name='字段')),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_filters', to='chart.Chart', verbose_name='图表')),
            ],
        ),
    ]
