# Generated by Django 2.2.19 on 2021-03-11 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0020_chartformfilter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chartcardfilter',
            old_name='value',
            new_name='_value_legacy',
        ),
        migrations.RenameField(
            model_name='filter',
            old_name='value',
            new_name='_value_legacy',
        ),
        migrations.RenameField(
            model_name='statisticfilter',
            old_name='value',
            new_name='_value_legacy',
        ),
    ]
