# Generated by Django 2.2.19 on 2021-03-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0022_auto_20210311_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimension',
            name='expression',
            field=models.TextField(blank=True, null=True, verbose_name='表达式'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='expression',
            field=models.TextField(blank=True, null=True, verbose_name='表达式'),
        ),
    ]
